### ISSUE TITLE
random bot skin idea

### ISSUE THREAD

**Issue by wartoz** [l3mpik/slither-feeder-bot#11]
there is actually setSkin(snake, number) and -1 for bots using same skin as you working, but can we do any bots connect with differents skins ( between 1 to 30 ) ?

**Comment by MinersMC** [comment]
u need to make a array with numbers.

**Comment by l3mpik** [comment]
Array? Easy i add this option today. Next 3h . : ) Now i working on spawn bot in same server after die or change.

**Comment by wartoz** [comment]
l3mpik i added you on skype can you accept my request iTwiGXDev

**Comment by l3mpik** [comment]
Sure

**Comment by anonymousxxx02** [comment]
random name and random skin #12

**Comment by wartoz** [comment]
thanks good job anonymous

**Comment by anonymousxxx02** [comment]
your wellcome ;)
