### ISSUE TITLE
random name and random skin

### ISSUE THREAD

**Issue by anonymousxxx02** [l3mpik/slither-feeder-bot#12]
add this in feeder.js at the top

---

var slithernames = {};

slithernames.nameList = [
  "nikos","AnonymousBots","xxx2" 
  ];

slithernames.getRandomName = function() {
    return slithernames.nameList[Math.floor((Math.random() \* slithernames.nameList.length))];
};
function rskin(){
return Math.floor((Math.random() \* 39)+1)};

---

 and change line 50 and 52 to 
`name: slithernames.getRandomName()`
`skin: rskin()`

**Comment by wartoz** [comment]
thanks bro

**Comment by anonymousxxx02** [comment]
your welcome ;)

**Comment by easyrider81** [comment]
Thanks very much random skins works. 
fyi skin: rskin() willl need skin: rskin(),

**Comment by l3mpik** [comment]
Nice idea. : )

**Comment by anonymousxxx02** [comment]
thank you for name i take the idea from ogar feeder bot

**Comment by wartoz** [comment]
D:\Users\iTwiGX\Documents\Koding Slither.io\updated\slither-feeder-bot-master>node feeder.js
D:\Users\iTwiGX\Documents\Koding Slither.io\updated\slither-feeder-bot-master\feeder.js:51
        skin: rskin()
        ^^^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3

D:\Users\iTwiGX\Documents\Koding Slither.io\updated\slither-feeder-bot-master>Pause
Appuyez sur une touche pour continuer...

**Comment by wartoz** [comment]
can you do a pullrequest

**Comment by easyrider81** [comment]
should look like this Wartoz, maybe missed the comma
<a href="https://gyazo.com/b12824e720a5f85cbc6b4d4e211b9cd2"><img src="https://i.gyazo.com/b12824e720a5f85cbc6b4d4e211b9cd2.png" alt="https://gyazo.com/b12824e720a5f85cbc6b4d4e211b9cd2"/></a>

I haven't used random names just skins.

**Comment by anonymousxxx02** [comment]
i don know how to make a pull reques :(
you can download the script from here http://pastebin.com/QLMud71a

**Comment by wartoz** [comment]
thanks

**Comment by sebakof** [comment]
alguien usa bots
