### ISSUE TITLE
Server [ I don't know how to run! ]

### ISSUE THREAD

**Issue by gamer2331** [l3mpik/slither-feeder-bot#15]
It doesn't work if i do node server

**Comment by gamer2331** [comment]
I'm on windows 10

**Comment by l3mpik** [comment]
Screen shot or something ?

**Comment by gamer2331** [comment]
Can't find module socket.io

**Comment by gamer2331** [comment]
it says that

**Comment by anonymousxxx02** [comment]
1. Download repo
2. Go to main path
3. Type in cmd npm install

**Comment by l3mpik** [comment]
Good community of this repo. Say thanks for help.

**Comment by gamer2331** [comment]
Thanks for help
