### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by anonymousxxx02** [l3mpik/slither-feeder-bot#16]
hey @l3mpik  can you add a changelog file so we can see what exactly you change every time you update the code

**Comment by l3mpik** [comment]
Sure : )

**Comment by anonymousxxx02** [comment]
thanks bro :) you are the best

**Comment by l3mpik** [comment]
Ehh.. no.  But thanks :D

**Comment by ghost** [comment]
good lempika is mobile slither and web version connected

**Comment by l3mpik** [comment]
Wut ? :D " lempika " ? :)))

**Comment by ghost** [comment]
lol typing error

**Comment by ghost** [comment]
😀 is mobile and web connected

**Comment by l3mpik** [comment]
Ohh.. haha :D Close? I make chat w8
