### ISSUE TITLE
Cmd

### ISSUE THREAD

**Issue by gamer2331** [l3mpik/slither-feeder-bot#18]
I'm new to js my question is how do you use cloud9? i saw someone else asked it but i didn't get the answers so good

**Comment by ghost** [comment]
clone the repo or download and transfer to c9 and open the script change th ip with port 8080,8081,8082 as they are the only working ports on c9.io and run client and server and play slither thats all

**Comment by ghost** [comment]
and make the c9.io public

**Comment by l3mpik** [comment]
yes, Very good answer! : )

**Comment by fadythegamer** [comment]
Didn't work for me :/

**Comment by ghost** [comment]
we help you but if your too lazy to search we cant help you mate not bieng harsh

**Comment by l3mpik** [comment]
Yes, i can help but i don't want make this for u. 

> clone the repo or download and transfer to c9 and open the script change th ip with port 8080,8081,8082 as they are the only working ports on c9.io and run client and server and play slither thats all

This is very good answer : )

**Comment by gamer2331** [comment]
I scerwed up in the cmd after i do node sever.js cant type anything anymore

**Comment by gamer2331** [comment]
help me

**Comment by anonymousxxx02** [comment]
look this video https://www.youtube.com/watch?v=AnoHEkmmsUE&list=WL&index=1
it gonna help you

**Comment by gamer2331** [comment]
I just need help with cmd right now

**Comment by l3mpik** [comment]
WTF? How old r u?  11 / 12? We don't support kids sory. : /

**Comment by anonymousxxx02** [comment]
WTF BRO
1.delete everything
2.download again the code
3.open cmd in code
4.type npm install

**Comment by l3mpik** [comment]
haha :D Question about age and he closed :D lol :D Wanna say something or close ?

**Comment by l3mpik** [comment]
Meeh , haha :D Nice fun xd

**Comment by fadythegamer** [comment]
im 12

**Comment by ghost** [comment]
no need to run bat in cloud9 just run server and client

**Comment by gamer2331** [comment]
I know how but Bots name:slither-feeder-bot
Connection!
Connection!
Connection!
and no bots coming
