### ISSUE TITLE
There lot to improve but it's a good start I guess

### ISSUE THREAD

**Issue by ghost** [l3mpik/slither-feeder-bot#2]
You can improve server.js and feedme.js. js and userscript is good but you you add other features and there's a lil trick to increase bots to a massive amount more the chither I had trouble changing everything but I finally did it 😊 better change the codes or wait for daqhan to make a specfic repo for feeder instead of lib

**Comment by l3mpik** [comment]
I thing today add "eat food" function. And optional bots line to player. But thanks for info! : )

**Comment by ghost** [comment]
;) good work i could help you if you need

**Comment by l3mpik** [comment]
Hmm.. what u mean? Give me skype, we can talk about this ;p

**Comment by ghost** [comment]
umm give urs and delete it after cuz rn im on my mobile

**Comment by l3mpik** [comment]
l3mpik@gmail.com <-- skype

**Comment by ghost** [comment]
ok delete

**Comment by ghost** [comment]
added micheal

**Comment by ghost** [comment]
guess you dont wanna work together
