### ISSUE TITLE
bot following mouse x,y idea

### ISSUE THREAD

**Issue by wartoz** [l3mpik/slither-feeder-bot#21]
possible?

**Comment by wartoz** [comment]
we can control the speed of bot and maybe give a direction to bots so they can eat around us or do some protection

**Comment by ghost** [comment]
wartoz stop spamming and code for yourself

**Comment by wartoz** [comment]
i'm working on just i'm here to collaborate don't seems your objective go away bro

**Comment by ghost** [comment]
but you steal and sell i heard in github

**Comment by l3mpik** [comment]
Easy, i don't care. Maybe i add mouse x,y controll

**Comment by wartoz** [comment]
l3mpik can you turn on skype i want to send you something
