### ISSUE TITLE
Skin update

### ISSUE THREAD

**Issue by anonymousxxx02** [l3mpik/slither-feeder-bot#22]
@l3mpik bro slither.io update skin so just change random math from 38 to 41
 Also please remove the GUI its not good and i cant even start bots with random skin & name because of GUI..Its easyer to change tha name from feeder or just make a config file like ogar feeder bot

**Comment by anonymousxxx02** [comment]
Also add a startserver.bat and startfeeder.bat for our noob friends

**Comment by easyrider81** [comment]
Same, can't start bots with the new GUI added.

**Comment by l3mpik** [comment]
Ohh sorry, today i update server/userscript,feeder. Sorry for problems.
