### ISSUE TITLE
socks4/5 and http support??

### ISSUE THREAD

**Issue by anonymousxxx02** [l3mpik/slither-feeder-bot#24]
@l3mpik bro can you add #socks4 #sock5 #http support just like ogar feeder bot???? i tried that yesterday but no succses :(

**Comment by wartoz** [comment]
socks5 support already exists dist/bot.js add this lines :

```
            } else if (mode === 'socks') {
                console.log('Mode socks, proxy', proxyServer);
                let temp = proxyServer.split(':');
                let socksIp = temp[0]
                let socksPort = temp[1];
                requestOptions.agent = new Socks.Agent({
                    proxy: {
                        ipaddress: socksIp,
                        port: socksPort,
                        type: 5
                    }
                });
            }
```

and change var mode = 'http';
to var mode = 'socks';

**Comment by anonymousxxx02** [comment]
@Wartoz yes i know that..i ask for something like ogar fedder bot

#socks4
   //sock4 proxies
#socks5
  //sock4 proxies
#http 
  //http proxiest

**Comment by wartoz** [comment]
hmm i see

**Comment by l3mpik** [comment]
i support only http and socks5 . Sorry.  Maybe later.

**Comment by yario-o** [comment]
https://github.com/dahquan/rattlesnake/issues/70

**Comment by yario-o** [comment]
@anonymousxxx02 I just add SOCKS4

**Comment by yario-o** [comment]
EDIT : I add socks4

**Comment by yario-o** [comment]
Multi Proxy Support of slither-feeder-bot : 
https://github.com/yario-o/slither-feeder-bot
Multi Proxy Support of rattlesnake : 
https://github.com/yario-o/rattlesnake/tree/SocksAndHTTP/

**Comment by yario-o** [comment]
Pull request : https://github.com/l3mpik/slither-feeder-bot/pull/31
