### ISSUE TITLE
update

### ISSUE THREAD

**Issue by ghost** [l3mpik/slither-feeder-bot#26]
u didnt update :/

**Comment by anonymousxxx02** [comment]
@kurama129 why you are waiting for update??? You have your own better bots :p

**Comment by l3mpik** [comment]
I have life lol :dancer:  i just back to home now, easy...

**Comment by anonymousxxx02** [comment]
@l3mpik ok sorry bro :(

**Comment by l3mpik** [comment]
- work XD Now. :D

**Comment by anonymousxxx02** [comment]
@l3mpik bro where are you from and what time is there ???

**Comment by ghost** [comment]
is there a way to increase bots or should i rewrite the feedeme.js

**Comment by anonymousxxx02** [comment]
I am getting 120 -180 bots in c9.io

**Comment by ghost** [comment]
image

**Comment by ghost** [comment]
i want bots to stay at 150 or 120 and not change

**Comment by anonymousxxx02** [comment]
Yes if @l3mpik make better reconnect script so bots stay at 120-150 it would be awsome

**Comment by WJKH** [comment]
Just noticed some limits recently, I can't connect more than 100 bots now.

**Comment by anonymousxxx02** [comment]
@kurama129 http://postimg.org/image/4u2wyfm0r/

**Comment by l3mpik** [comment]
Poland, now 00:40 06.01
