### ISSUE TITLE
socks and http support

### ISSUE THREAD

**Issue by yario-o** [l3mpik/slither-feeder-bot#3]
please add http and socks support like ogar feeder bots

**Comment by CupidStunts** [comment]
im having some issues with this on proxies

im using same proxy list with the rattlesnake repo. & on this i barely get any spawning?
im using http & proxys have been checked?

**Comment by l3mpik** [comment]
I make little thing to protect this script befor 1 person. Script use http and socks5. Default is socks5 :)

**Comment by l3mpik** [comment]
If u change bot nick to other than 3l3mpik and u want other. Just add 3 before bots nick.

**Comment by CupidStunts** [comment]
thx dude, i already started remaking the scripts. thx a lot dude. it needed to be done this way ;)

**Comment by mayed505** [comment]
@l3mpik  why do we have to add 3 before nick?
