### ISSUE TITLE
VPS - C9.IO

### ISSUE THREAD

**Issue by InfiniteIPProwess** [l3mpik/slither-feeder-bot#30]
Hello. Using the rattlesnake bots, I was able to connect the bots to slither.io via cloud 9 (vps) but I am having some, well alot, of difficulty to connect these bots with cloud 9. Is there a tutorial or something that can help?

**Comment by anonymousxxx02** [comment]
I can help you tell me your problem

**Comment by InfiniteIPProwess** [comment]
It wont run...do you have skype or something?

**Comment by InfiniteIPProwess** [comment]
The problem is, in the feeder, it just says waiting for client...?
This happens to me with and without a vps..
and I think I am doing everything correctly (running server.js and feeder.js and then going to slither.io and clicking on)

**Comment by anonymousxxx02** [comment]
Give me the link of c9.io and give me rw permision

**Comment by AlexandriteErikParacelsus** [comment]
c9.io is no VPS, if you don't want to get banned on c9.io please don't use bots on c9.

**Comment by David1ali12** [comment]
dont use c9 you will get banned forever

**Comment by InfiniteIPProwess** [comment]
hey anonymousxx02...I got it to work on cloud 9 but the problem is, with or without the vps, it says waiting for client when i run node feeder.js (I also do node server.js and press connect) and t still doesnt work? What might be the issue...who cares about vps for now...it just says waiting for client..

**Comment by anonymousxxx02** [comment]
@InfiniteIPProwess bro this script to work need some changes. Just download working script in my YT chanel

**Comment by coolness13370** [comment]
The Chrome Web store has an app (
https://chrome.google.com/webstore/detail/slitherio-mods-zoom-unloc/eogeabecipmckmihpmkgjbghbffcebcf
)
It gives you the slither.io zoom mod, Changeing skins in game, bots (you
become the bot), more skins, and the chat on the gmae screen. Have you
tried it out yet?

Hope you try and enjoy this slither.io mod!

**Comment by ItzLevvie** [comment]
.

**Comment by InfiniteIPProwess** [comment]
@anonymousxxx02 Sure..but please put the download as soon as you can (Slither V2)

**Comment by anonymousxxx02** [comment]
@InfiniteIPProwess i am making some changes but i will try to puplish as soon as possible
