### ISSUE TITLE
HTTP & PROXY + TYPE & PORT

### ISSUE THREAD

**Issue by InfiniteIPProwess** [l3mpik/slither-feeder-bot#33]
I was wondering if it is possible to use http proxies and socks proxies together which would be more efficient for me and if it was possible, how do I do it? Also, it says only socks 5 proxies are allowed to be used and only http proxies with port 80 is allowed to be used. So, how can I make it allow socks 4 as well and other http ports, is it possible, how do I do it?

**Comment by anonymousxxx02** [comment]
@InfiniteIPProwess yario-o add socks4/5 and http proxy at the same time but is not working good

**Comment by coolness13370** [comment]
The Chrome Web store has an app (
https://chrome.google.com/webstore/detail/slitherio-mods-zoom-unloc/eogeabecipmckmihpmkgjbghbffcebcf
) It gives you the slither.io zoom mod, Changeing skins in game, bots (you
become the bot), more skins, and the chat on the gmae screen. Have you
tried it out yet?

Hope you try and enjoy this slither.io mod!

**Comment by yario-o** [comment]
@anonymousxxx02  now it work good

**Comment by anonymousxxx02** [comment]
@yario-o  i am gonna try this later

**Comment by InfiniteIPProwess** [comment]
@anonymousxxx02 @yario-o wait so I can use http proxies and socks 5 and socks 4 ALL at the same time? Can I have the link to the download please?

**Comment by anonymousxxx02** [comment]
@yario-o bro i am getting this problem `[ReferenceError: mode is not defined]`

**Comment by anonymousxxx02** [comment]
@InfiniteIPProwess this still isnt working

**Comment by yario-o** [comment]
@anonymousxxx02 it work now?

**Comment by yario-o** [comment]
@InfiniteIPProwess Download it here : https://github.com/l3mpik/slither-feeder-bot/issues/33

**Comment by easyrider81** [comment]
Sorry but still not working for me.

Errors have gone but when I press connect in game the feeder cmd says "change to SOCKS proxy" but no bots connect. I've edited the proxy file with #SOCKS5 above my list of SOCKS5 proxies. Not sure what the problem is....

**Comment by anonymousxxx02** [comment]
@yario-o bro i am gonna try this later and i am gonna tell you

**Comment by anonymousxxx02** [comment]
@yario-o still not work : (

**Comment by yario-o** [comment]
@anonymousxxx02  @easyrider81 I don't know why my multi proxy bots don't work with l3mpik version but it work with rattlesnake version
