### ISSUE TITLE
"Waiting for client"

### ISSUE THREAD

**Issue by TDashDog1** [l3mpik/slither-feeder-bot#36]
Hi! This issue happens on both my VPS and PC. I've installed everything that it asks for, including some dependencies not satisfied in package.json (socket.io and socks). Server.js shows a connection, but feeder.js just shows "Waiting for client". I'd really like some help. Thanks!

**Comment by anonymousxxx02** [comment]
This script need some changes to work.  I have fix this and you can download it from here https://youtu.be/fNn-YzHZpp0
