### ISSUE TITLE
Bot doesnt reconnect on death tested

### ISSUE THREAD

**Issue by mayed505** [l3mpik/slither-feeder-bot#39]
Bot doesnt reconnect on death tested

**Comment by Numan1982** [comment]
ive jusst updated my feeder and userscript now bots reconnect! also i added when a bot disconnects from a proxy it tries to reconnect back!

**Comment by l3mpik** [comment]
nice ;p

**Comment by Lok0n** [comment]
@Numan1982 so share it

**Comment by anonymousxxx02** [comment]
@mayed505 bots recconect after death but the problem is that the bots reconect to the old server.. If you play at the same server you will have no problem but if you change server the bots  will recconect to new server but also they will spawn on the old server too. You have to call the bot.close() before change server

**Comment by mayed505** [comment]
@anonymousxxx02 thanks for the help i will try and keep you informed.
EDIT: my bots come to new server i have fixed that, problem when they come to new server its works fine but after bot death they dont connect but even the connect they wont follow.

**Comment by anonymousxxx02** [comment]
@mayed505 my bots work fine...i was playing to the same party for about 1 hour with 300 bots and i had no problem...also you are running bots your pc or vps

**Comment by ravyn120** [comment]
@mayed505 If they connect and don't follow you why don't you just continuously update the x,y just like when the bots start? Probably would make it smoother since it might not call to update x,y. I use node websockets instead of socket.io so yeah not sure.

**Comment by mayed505** [comment]
@ravyn120 do you have skype?

**Comment by mayed505** [comment]
@anonymousxxx02 found out a way to make them go to new server but i dont know the code so heres what we need" So when we go to new server bots go to the new server + old server at the sametime"

So what we will need " on server change disconnect all proxies and reconnect them to new server"

**Comment by mayed505** [comment]
@ravyn120  @l3mpik  @Lok0n  @anonymousxxx02  do you know how?

**Comment by ravyn120** [comment]
@mayed505 I don't know maybe there's a way in the proxy agent.

**Comment by anonymousxxx02** [comment]
#https://github.com/dahquan/rattlesnake/issues/61

**Comment by InfiniteIPProwess** [comment]
@anonymousxxx02 when will u be posting the bots on ur channel?
