### ISSUE TITLE
Not finished ...

### ISSUE THREAD

**Issue by yario-o** [l3mpik/slither-feeder-bot#4]
In package.json name is invalid : it is Slither Feeder Bot
It must be : Slither-Feeder-Bot
In package.json too there isn't socket.io so npm install don't install socket.io

**Comment by l3mpik** [comment]
Ohh.. Thanks i don't see this xD Sorry. I update now : )

**Comment by ItsVoxility** [comment]
Does the snakes follows you when hopping servers?

**Comment by ItsVoxility** [comment]
Im not home to check right now.
