### ISSUE TITLE
probelm with connect 

### ISSUE THREAD

**Issue by ghost** [l3mpik/slither-feeder-bot#41]
Hello all, I’m have discovered a problem, so when you join the first server the first time bots join fine but when you die, you join a new server right?… So bots comes to new server but heres the problem: the bots go on old_server and new_server at the same time which causes bots not to follow on death or not even reconnect since it will be back to old_server. So what i have found is that we need to disconnect the proxies that are connected to old_server and reconnect it to new_server proxy/server i should say i couldn’t find the right code to do it. So can anyone try to help?

**Comment by l3mpik** [comment]
Yes i fix it and upload maybe next day.
