### ISSUE TITLE
1 K Bots ? : ) !! UPDATED !!

### ISSUE THREAD

**Issue by l3mpik** [l3mpik/slither-feeder-bot#42]
https://www.youtube.com/watch?v=-gbPzJPymCc

Blah...Blah... meehh...soo? Update this weekend?  xD

**Comment by David1ali12** [comment]
cool cant wait

**Comment by l3mpik** [comment]
Thanks : ) Only 2 days. Just make better gui

**Comment by anonymousxxx02** [comment]
Awesome bro!!!! Where are you running bots

**Comment by Salvationdk** [comment]
still getting "Waiting for client!" 
have installed the userscript and it pops up on the game but nothing else happens

**Comment by Lok0n** [comment]
@Salvationdk @l3mpik me too "waiting for client!"

**Comment by David1ali12** [comment]
I have same problem btw "Waiting for client!"  when hosting on my vps

**Comment by mayed505** [comment]
@l3mpik where you got ur proxies from please say

**Comment by l3mpik** [comment]
1. Maybe they us some edited files.
2. Look for feeder.js at line 13: 

ex. var socket = require('socket.io-client')('ws://127.0.0.1:4000'); <--- Maybe is the problem with port : ) 
1. I use VPS  ( 2x 1,5 ghz | 2 gb ram | 250 mbi/s connection ) 
2. Enyoj !

**Comment by anonymousxxx02** [comment]
@l3mpik in c9.io i am getting 400-500 bots

**Comment by l3mpik** [comment]
Nice : )

**Comment by mayed505** [comment]
@l3mpik where you got your proxies from please? i want like your bots

**Comment by l3mpik** [comment]
@mayed505  give me sec : )

**Comment by l3mpik** [comment]
@mayed505  can u tell me what is this ? http://imgur.com/oLApoHh ? Hmm.. When i click to github link i get redirect to my project. WTF ?

**Comment by mayed505** [comment]
@l3mpik yea about that..... i created a project like yours and took it down since youtuber skids stole my gui and all files and sold me them YES THEY SOLD IT....  Since they saw my project is done i redirected it to yours :)

**Comment by mayed505** [comment]
@l3mpik btw can you send me the link where u get your proxies from?

**Comment by l3mpik** [comment]
@mayed505 

http://www.vipsocks24.net/

http://www.live-socks.net/

Here is script for tempermonkey : 
Proxy saver: http://pastebin.com/8VPGtgE2
Proxy saver server: http://pastebin.com/ygZ3fHtk

:))

**Comment by David1ali12** [comment]
thx @l3mpik  i used procees.env.ip and worked

**Comment by ghost** [comment]
what

**Comment by anonymousxxx02** [comment]
@David1ali12 @Salvationdk @Lok0n @mayed505
 #45
