### ISSUE TITLE
lempik release

### ISSUE THREAD

**Issue by ghost** [l3mpik/slither-feeder-bot#43]
hey lempik you said you fixed the issue i posted and u said you will release oday if you will release release it now

**Comment by l3mpik** [comment]
Is updated xD

**Comment by ghost** [comment]
so is it released

**Comment by l3mpik** [comment]
yup

**Comment by ghost** [comment]
link

**Comment by ghost** [comment]
and why exe file

**Comment by ghost** [comment]
for startbots

**Comment by l3mpik** [comment]
Cuz i code C++ .
