### ISSUE TITLE
count 0 bot spawning in localhost

### ISSUE THREAD

**Issue by wartoz** [l3mpik/slither-feeder-bot#44]
http://i.imgur.com/PPhES1j.png
and there is a syntax mistake in server.js line 19 "}" remove it

**Comment by l3mpik** [comment]
17:if (!!process.env.SLITHER_PER_PROXY) {
18:  perProxy = parseInt(process.env.SLITHER_PER_PROXY)
19: } <-- end of if . :)

**Comment by l3mpik** [comment]
I thign u need to set port in feeder.js to same like server port. ;p

**Comment by wartoz** [comment]
it's the same port 3000 everywhere

**Comment by wartoz** [comment]
and they don't spawn

**Comment by l3mpik** [comment]
Hmm.. I in user script same ?

**Comment by wartoz** [comment]
yes

 if (vps == 1) {
    var socket = io.connect('ws://188.68.252.227:3333');
    $("#mode").text('VPS');
} else {
    var socket = io.connect('ws://127.0.0.1:3000');
    $("#mode").text('LOCAL');
}

and i'm in localhost mode

**Comment by l3mpik** [comment]
emm... hmm..

**Comment by wartoz** [comment]
i tried your old versions they works but the updated not ^^

**Comment by l3mpik** [comment]
I update now try now.

**Comment by wartoz** [comment]
http://i.imgur.com/fXLZIlv.png
error

**Comment by wartoz** [comment]
still no spawning

**Comment by l3mpik** [comment]
lol, u can't delete on " } " ? now is fixed.

**Comment by wartoz** [comment]
i know but still no spawning

**Comment by wartoz** [comment]
same as first screenshot

**Comment by wartoz** [comment]
status: 0

**Comment by l3mpik** [comment]
lol, idk what u doing bad .. lol , for me everything is working good.

**Comment by wartoz** [comment]
:/

**Comment by l3mpik** [comment]
Skype share screen ?

**Comment by wartoz** [comment]
connect you

**Comment by wartoz** [comment]
you can try on my vps i cloned your git

**Comment by ghost** [comment]
im having same issue it says status 0

**Comment by wartoz** [comment]
:/

**Comment by ghost** [comment]
:/

**Comment by ghost** [comment]
maybe hes trolling us

**Comment by wartoz** [comment]
no he tried to fix on my pc but not work

**Comment by ghost** [comment]
can we try fix it

**Comment by ghost** [comment]
does it work in vps

**Comment by anonymousxxx02** [comment]
Guys i am gonna check new update later and if i make it run i will help you

**Comment by ghost** [comment]
ok

**Comment by anonymousxxx02** [comment]
@Wartoz @kurama129 i find the problem

**Comment by l3mpik** [comment]
Where is the problem? For me script working good.

**Comment by anonymousxxx02** [comment]
@l3mpik for you it work because in your vps you use old bot.js(before merge with yario-o)... in the github is the merged bot.js

**Comment by l3mpik** [comment]
fixedd
