### ISSUE TITLE
it doesnt work status 0 i kept al the ports right and etc server is connection only the feeder is not spwaning but it is also connected

### ISSUE THREAD

**Issue by ghost** [l3mpik/slither-feeder-bot#45]
can you fix this

**Comment by anonymousxxx02** [comment]
@kurama129 i am gonna check script later and if i fix it i will tell you

**Comment by l3mpik** [comment]
For me every thing is working very good . Idk what happend : /

**Comment by anonymousxxx02** [comment]
@l3mpik bro your script dont work.... I run it without any change and dont work..
i make some changes in the script and i only get 6 bots :(

**Comment by l3mpik** [comment]
looolll :D i get 200-350 with vps. loool every one give me info about don't working script but i just upload my script from vps XD

**Comment by anonymousxxx02** [comment]
@l3mpik lol i find the problem ;) 
the proble is in bot.js is the merge with yario-o......
just upload old bot.js and the bots will work fine

#44

**Comment by l3mpik** [comment]
:DDD ciii...xd

**Comment by l3mpik** [comment]
fixed
