### ISSUE TITLE
new secret skin "Google Store"

### ISSUE THREAD

**Issue by wartoz** [l3mpik/slither-feeder-bot#47]
Change skin page :
skin preview -> http://i.imgur.com/a6YAehj.jpg

> F12 > Console tab > enter "setSkin(snake, 42)"
> Enjoy
> - for random skins -> return Math.floor((Math.random() \* 42)+1)};

**Comment by ghost** [comment]
wartoz did you fix the 0 stauts error

**Comment by Wartoz** [comment]
http://i.imgur.com/a6YAehj.jpg

**Comment by wartoz** [comment]
and no the updated version still not workfor me /FIXED/

**Comment by ghost** [comment]
even me ;/

**Comment by anonymousxxx02** [comment]
For me its work fine

**Comment by ghost** [comment]
worked fine but im not getting 700 bots local

**Comment by anonymousxxx02** [comment]
@kurama129 you need a killer pc to get 700 bots

**Comment by CupidStunts** [comment]
@kurama129  its impossible to get 700 bots lol, why do you lie lol or not understand how slither servers  works lol, ive seen you call you people out & you are the biggest nub ive ever seen lol.

honestly git it is full of so many skids nowadays its too funny. java isnt even my thing but i learning quick & tbh its hilarious too watch you fakers!

**Comment by ghost** [comment]
fyi im not a skid but you are and this isnt java its javascript and instead judging someone why dont you get a life and do your work lil kid  so stfu and fuck off

**Comment by anonymousxxx02** [comment]
@kurama129 @CupidStunts 
https://snag.gy/XZjGYI.jpg
https://snag.gy/AhcEMz.jpg
https://snag.gy/Ff0mGw.jpg

**Comment by CupidStunts** [comment]
@kurama129 im definitely older than you kiddo lol, i just find it funny your posting here all the time & waiting on updates.. but a couple of weeks ago you said you had remade with eat food code etc & was calling people left & right. that was all lies haha..if IRC its.. lmfao :)
https://github.com/dahquan/rattlesnake/issues/62 

and @anonymousxxx02 you literally cant get 700 bots, unless your the only guy in the server. :/
look at your bottom left of screen, players in the server vs botcount? ;)

**Comment by ghost** [comment]
i did make it and why should i make it opensource

**Comment by ghost** [comment]
as if you share everything

**Comment by wartoz** [comment]
@l3mpik connect please i want to show you something
