### ISSUE TITLE
stillnot working after update status 0

### ISSUE THREAD

**Issue by ghost** [l3mpik/slither-feeder-bot#48]

**Comment by anonymousxxx02** [comment]
@kurama129 where are you running bots????

**Comment by wartoz** [comment]
i tried localhost and on my vps idk why they don't spawn :(

**Comment by ghost** [comment]
i run on local host

**Comment by ghost** [comment]
anonymous you could help by giving me your files

**Comment by wartoz** [comment]
now it works but the logs show 0 spawn but the bots coming to me
http://i.imgur.com/nkeQPkm.jpg

**Comment by l3mpik** [comment]
U care about logs? Bots is working. Don't care about logs is still dev. version of bots. lool @kurama129  stop making stupid issues, just update files. -,-

**Comment by l3mpik** [comment]
Please stop making stupid issues. Bots working, if u doing something bad is not my problem. Script is working.
