### ISSUE TITLE
someone selling this sliher bots for money

### ISSUE THREAD

**Issue by ghost** [l3mpik/slither-feeder-bot#50]
https://www.youtube.com/watch?v=u6UVG_5ixwI his name is samgamesyt

**Comment by wartoz** [comment]
wtf he got this amount of bots

**Comment by wartoz** [comment]
and this guy is a kid just write " samgamesYT exposed on YT" https://www.youtube.com/watch?v=7XDxPhNQZP0

**Comment by wartoz** [comment]
he needs this money to get more candies respect him

**Comment by l3mpik** [comment]
Any proof is my script ?

**Comment by wartoz** [comment]
l3mpik i have the same skin as the video by default

**Comment by wartoz** [comment]
can you turn on skype i have some questions

**Comment by l3mpik** [comment]
He record with zoom... Bitch.

**Comment by anonymousxxx02** [comment]
@l3mpik they are your bots check https://www.youtube.com/watch?v=K7kAVFaJuPw

**Comment by l3mpik** [comment]
Fucking bitch...

**Comment by l3mpik** [comment]
He delete vid :))

**Comment by anonymousxxx02** [comment]
maybe he saw this issue :p

**Comment by l3mpik** [comment]
No. i write to him.

**Comment by anonymousxxx02** [comment]
Ok :)

**Comment by ghost** [comment]
nice i trolled him for you :)

**Comment by wartoz** [comment]
@l3mpik need help http://i.imgur.com/oX23Bjg.jpg
http://i.imgur.com/s3oV4Ak.jpg

**Comment by ghost** [comment]
you mean you need help with that on off button

**Comment by wartoz** [comment]
no this works

**Comment by l3mpik** [comment]
lols

**Comment by Numan1982** [comment]
wartoz u can stfu ur selling ur bots for $8usd and u scammed me before cunt. and im loving ur ip man ;) 82.233.76.192 << its what u get

**Comment by Numan1982** [comment]
cant wait to release this

**Comment by ghost** [comment]
whos ip is that and what your gonna do with that

**Comment by Numan1982** [comment]
its wartozs ip he scammed me.
