### ISSUE TITLE
tried everything still getting status 0 [FIXED!!!!!!]

### ISSUE THREAD

**Issue by Numan1982** [l3mpik/slither-feeder-bot#51]

**Comment by l3mpik** [comment]
Screen Shot, where script say "status 0 " ?

**Comment by Numan1982** [comment]
i got it to fix now but the bots dont spawn? or come to me it said i have 100+ bots but none came or spawned by the looks of it. my skype is sh00t4it

**Comment by l3mpik** [comment]
Screen shot of this "status 0 " ? :) Idk what is status 0 .. hmm.. what is this? Bots working.

**Comment by anonymousxxx02** [comment]
@l3mpik by status 0 he mean that bot count is 0(the bots don't spawn)

**Comment by l3mpik** [comment]
I know, but is not fucking status 0; Damn is hard to say " I have 0 bots in console, why ? " ... omg. Is becouse the console.log (fucking status 0 -,- ) ; is out of loop. This is reason why Script say "0 bots" ... ehh..

**Comment by Numan1982** [comment]
that didnt help me.
I HAVE FIXED THE ISSUE ABOUT BOT COUNT BUT BOTS DONT SPAWN IT SAYS I HAVE OVER 100BOTS BUT NONE COME OR SPAWN  AND I DIDNT CONNECT TO A Different SERVER
sorry for caps :P

**Comment by l3mpik** [comment]
damn... skype?

**Comment by l3mpik** [comment]
FIXED -,-
