### ISSUE TITLE
someone can help?

### ISSUE THREAD

**Issue by wartoz** [l3mpik/slither-feeder-bot#56]
GUI preview -> http://i.imgur.com/puqYNwB.jpg
i found how to shows the gX and gY positions in console log with l3mpik version but someone can help me to add this function/information in GUI? more info add me on skype : iTwiGXDev

console logs
http://i.imgur.com/mdqxJdC.png

**Comment by anonymousxxx02** [comment]
I alredy have done that   https://youtu.be/VMy-8QpVsZw

Also now i removed l3mpik Gui and i made bots connect every time you connect in a new server..no need to turn on off bots anymore.

**Comment by wartoz** [comment]
and what's your skype i want to tell you something

**Comment by anonymousxxx02** [comment]
Sorry bro i dont use skype :/

**Comment by wartoz** [comment]
you got a discord?

**Comment by anonymousxxx02** [comment]
I only use gmail also i dont use skype,discord ,etc because i dont know to speek very good english :(

**Comment by wartoz** [comment]
i just want to pm you text

**Comment by anonymousxxx02** [comment]
You can pm me in my gmail anonymousx023x@gmail.com
