### ISSUE TITLE
I got like 100 proxies socks and doesnt work

### ISSUE THREAD

**Issue by mayed505** [l3mpik/slither-feeder-bot#6]
help me where can i get good proxies?

**Comment by ghost** [comment]
its not a pronlem with proxies the code is bad

**Comment by ghost** [comment]
problem

**Comment by mayed505** [comment]
@kurama129 i fixed it it ws a stupid protection by l3mpik that you had to add the number 3 at the begging of the bot nick but i removed that it was a stupid protection LMAO

**Comment by anonymousxxx02** [comment]
@mayed505 can you tell me how exactly you fix that

**Comment by CupidStunts** [comment]
```
        if (typeof proxyServer === 'string') {
            var AUTH = process.env.PROXY_AUTH || null;
            if(parseInt(_im_p) === 3){var mode = 'socks';}
            if (proxyServer.indexOf('socks') === 0) {
                mode = 'socks';
            }
```

change to

```
  if (typeof proxyServer === 'string') {
    var AUTH = process.env.PROXY_AUTH || null;
    var mode = 'http';
    if (proxyServer.indexOf('socks') === 0) {
      mode = 'socks';
    }
```

remove this also _im_p    =  name;

**Comment by anonymousxxx02** [comment]
this doesnt exist in the code i have
`if(parseInt(_im_p) === 3){var mode = 'socks';}`

**Comment by CupidStunts** [comment]
then your all good i guess ;) its in dist/bot.js

**Comment by anonymousxxx02** [comment]
ok thanks bro :)

**Comment by mayed505** [comment]
@CupidStunts i did that before i posted this :)

**Comment by l3mpik** [comment]
Stupid protection,lol lmao lol3 lol2,..Soo if u "pro" why u don't make script urself? hahha ^^

**Comment by mayed505** [comment]
@l3mpik first, i was testing your script so i can decide whenever if i should use yours and add more features or code from scratch.....secondly,because i felt that project of the " 3 " was stupid why did you even added that?

**Comment by CupidStunts** [comment]
as a protection so a million skids on youtube dont post it & claim that they made it for subs etc?
thx l3mpik...it threw me off on what i was doing at the time lol ;) I appreciate the code mate

**Comment by ghost** [comment]
and you guys revelead it 😑 but its ok😀

**Comment by ghost** [comment]
btw how many bots you grt

**Comment by mayed505** [comment]
@CupidStunts your removal code it wrong its.. var mode = 'socks';   and not var mode = 'http'; just saying that.
