### ISSUE TITLE
Please add a better http support :)

### ISSUE THREAD

**Issue by mayed505** [l3mpik/slither-feeder-bot#61]
Hello, i own a dedicated http proxies than socks sadly so all my proxies work 100% but the http ports are like XXXX:8083 XXXX:8081 and so on so these kind of http wont work could you add the http support from ogar-feeder-bots because the current http support is really bad.
Thanks.

**Comment by mayed505** [comment]
bump.

**Comment by l3mpik** [comment]
I read much about your issuses, make own http support. I don't wanan make any update cuz people start sell this. : ) Like feeder bot, u can port features from ogar feeder bot or wait for idiot who make 100% working slither bot and people start mass sell this for 0.5$ and botting all servers. 

Now the slither-feeder-bot is for people with brain! : )
