### ISSUE TITLE
Make it so when you die the script automatticly restarts itself

### ISSUE THREAD

**Issue by MineMooreALT** [l3mpik/slither-feeder-bot#62]
in the tittle

**Comment by mayed505** [comment]
@MineMooreALT why do u need that?

**Comment by Lok0n** [comment]
@MineMooreALT @l3mpik good idea 
@mayed505 cuz it's annoying

**Comment by mayed505** [comment]
@Lok0n wtf am i the only one that my bots rejoin the new server follows me?

**Comment by mayed505** [comment]
@Lok0n @MineMooreALT i can add it if u guys want it :3

**Comment by Lok0n** [comment]
yes. PR please "-"

**Comment by Lok0n** [comment]
pullrequest ? @mayed505

**Comment by mayed505** [comment]
@Lok0n i changed my mind i wont do it since people would sell it...

**Comment by Lok0n** [comment]
thanks for your useless help @mayed505

**Comment by MineMooreALT** [comment]
bruh dude i hate having to refresh ever time i wanna get bots again

**Comment by Lok0n** [comment]
same i hope @l3mpik add this new feature soon

**Comment by anonymousxxx02** [comment]
@Lok0n l3mpik already have add this feature.... Every time you change server the bots disconect from old server  and connect to new one
