### ISSUE TITLE
waiting for client and console error

### ISSUE THREAD

**Issue by easyrider81** [l3mpik/slither-feeder-bot#7]
getting these errors in console and bots not connecting
<a href="https://gyazo.com/801313f95275d8c272e4a764eb03e989"><img src="https://i.gyazo.com/801313f95275d8c272e4a764eb03e989.png" alt="https://gyazo.com/801313f95275d8c272e4a764eb03e989"/></a>

**Comment by anonymousxxx02** [comment]
@easyrider81 did you run server.js at first???

**Comment by easyrider81** [comment]
yup server running first

<a href="https://gyazo.com/4ba1fd9fad4987abe2f45926b666543d"><img src="https://i.gyazo.com/4ba1fd9fad4987abe2f45926b666543d.png" alt="https://gyazo.com/4ba1fd9fad4987abe2f45926b666543d"/></a>

**Comment by anonymousxxx02** [comment]
you are running bots in vps???

**Comment by easyrider81** [comment]
no local

**Comment by anonymousxxx02** [comment]
sorry i cant help you :(  i cant understand from console i must see the script to help you

**Comment by anonymousxxx02** [comment]
@easyrider81 i just test bots in local they work

**Comment by sandor111** [comment]
You need too change: Slitherio feeder bot to
Slitherio-feeder-Bot

**Comment by easyrider81** [comment]
Already changed the json and installed socket.io also.

Got it working now by editing code myself.

**Comment by l3mpik** [comment]
Fixed

**Comment by gamer2331** [comment]
I get the same thing to on cloud9
