### ISSUE TITLE
How do you use cloud9 as vps

### ISSUE THREAD

**Issue by MineMooreALT** [l3mpik/slither-feeder-bot#8]
I have dragged all files into cloud9 shared it and changed the ip in the userscript too
"ws://www.test-project-mine1o21.c9users.io:3000" But when i connect with the server running first it dosent not detect me is there some thing i need to change or is it just cloud 9 i have made the files and everything public so it should have no problem connect i have set this up the same way as ogar-feed-bot

**Comment by sandor111** [comment]
Please think yourself its so easy

**Comment by MineMooreALT** [comment]
I'm honestly qlue less i am new to js

**Comment by easyrider81** [comment]
Did you also change in userscript line 13 var vps = 0; to var vps = 1;

**Comment by MineMooreALT** [comment]
yes

**Comment by easyrider81** [comment]
how are you loading? server, feeder, slither, play, top left red button?

**Comment by MineMooreALT** [comment]
I load up the server go to slither.io click play normally it should detect me in server nyway i startup the feeder and click off to turn it too on and nothing happens

**Comment by easyrider81** [comment]
load server and feeder first then load your slither page and play

**Comment by MineMooreALT** [comment]
tried that
didnt work

**Comment by anonymousxxx02** [comment]
Is so easy.. c9.io work only in port 8080 ,  8081, 8082 so just change all the ports to 8080

**Comment by MineMooreALT** [comment]
omfg i'm so stupid
