### ISSUE TITLE
bots don't follow after die/respawn

### ISSUE THREAD

**Issue by wartoz** [l3mpik/slither-feeder-bot#9]
i have to reconnect the bots again after every deaths

**Comment by easyrider81** [comment]
Yep I noticed that too. Have to press top left button off and on again.

**Comment by wartoz** [comment]
rattlesnake bots follow after deaths i think it miss a part in feeder

**Comment by anonymousxxx02** [comment]
I thin thats the broblem is every time you die the server change..so just add a script that let you chose the server you want to connect and every time you die you will respawn in tha same server
Sorry for bad english ;)

**Comment by wartoz** [comment]
no i see the same leaderboard

**Comment by easyrider81** [comment]
yeah same server same leaderboard

**Comment by anonymousxxx02** [comment]
The broblem its not in the script...... I play  in tha same server and bots follow me every time

**Comment by wartoz** [comment]
the problem is you have to relaunch every time you death

**Comment by wartoz** [comment]
after your death bots don't come to you like they don't have the position

**Comment by wartoz** [comment]
x , y

**Comment by easyrider81** [comment]
could the console error I previously posted back this up?

<a href="https://gyazo.com/801313f95275d8c272e4a764eb03e989"><img src="https://i.gyazo.com/801313f95275d8c272e4a764eb03e989.png" alt="https://gyazo.com/801313f95275d8c272e4a764eb03e989"/></a>

can't get the xx coordinates.

**Comment by CupidStunts** [comment]
in the user script add a value to update speed & see if that helps

setInterval(function() {

```
if (window["snake"] !== undefined) {

    var x = snake.xx;
    var y = snake.yy;

    socket.emit('pos', x, y);

}
```

}, 200);

if just shows update speed then its probably the problem ;)

**Comment by anonymousxxx02** [comment]
I also get that error cant get the xx coordinates but bots work find and i dont have to relaunch the bots after death

**Comment by l3mpik** [comment]
I fix this just give me 30 min

**Comment by wartoz** [comment]
alright

**Comment by wartoz** [comment]
@CupidStunts same, bots don't come after respawn

**Comment by l3mpik** [comment]
Working on this now. Be patient.
